name: time_of_war
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  shared_preferences: ^2.5.5
  home_widget: ^0.9.3
  flutter:
    sdk: flutter
  image_picker: ^1.2.2
flutter:
  uses-material-design: true
